version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/app/contracts"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/app/contracts-casper/compliance-oracle"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/app/contracts-casper/identity-registry"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/app/contracts-casper/token-coupon"
    schedule:
      interval: "weekly"
